version: '3.9'
services:
  frontend:
    container_name: blog-vue-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    networks:
      - custom
    depends_on:
      - backend
    profiles:
      - frontend-only
      - full-deploy

  # FastAPI app
  backend:
    container_name: blog-fastapi-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      FASTAPI_APP_MODE: PROD
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongodb
    profiles:
      - backend-only
      - full-deploy

      # MongoDB
  mongodb:
    image: mongo:6.0.8
    container_name: blog-mongodb
    restart: always
    env_file:
      - .env.production
    ports:
      - "27017:27017"
    volumes:
      - blog_mongo_data:/data/db
    networks:
      - custom
    profiles:
      - mongodb-only
      - backend-only
      - full-deploy

volumes:
  blog_mongo_data:
    name: blog_mongo_data

networks:
  custom:
    driver: bridge