version: '3.9'

services:
  mongodb:
    image: mongo:6.0.8
    container_name: blog_mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: