# Общие настройки
prompt: "Я хочу, чтобы ты выступил в роли писателя. Я предоставлю вам заголовок статьи, и вы ее напишете.
Моя первая просьба звучит так: Напиши статью (не менее 100 слов) для заголовка '{title}', с следующими тегами: '{tags}' и ключевыми фразами: '{key_phrases}'.
Текст статьи должен быть отформатирован следующими HTML тегами: <b>, <i>. В ответе напиши только текст статьи, без заголовка и отдельного упоминания тегов"
model: "gpt-3.5-turbo"

# Temperature & tokens
temperature: 0.5
#max_tokens: 1000