# Общие настройки
prompt: "Напиши статью (не менее 100 слов) про '{title}' с следующими тегами: '{tags}' и ключевыми фразами: '{key_phrases}'.
Текст статьи должен быть оформлен в Markdown формате.
В ответе напиши только текст статьи, без заголовка и отдельного упоминания тегов"
model: "gpt-3.5-turbo"

# Temperature & tokens
temperature: 0.5
#max_tokens: 1000